// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGHQy6POAHursOLXU45hi2buYcWh_pSHg',
    appId: '1:268965482512:web:1d920d7c802fdd0cd9fa95',
    messagingSenderId: '268965482512',
    projectId: 'gestion-inventario-zaitec',
    authDomain: 'gestion-inventario-zaitec.firebaseapp.com',
    storageBucket: 'gestion-inventario-zaitec.firebasestorage.app',
    measurementId: 'G-H2NQGF672B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmxgwzziXWqyTcOvlGCZ_3Uync66ZjH4I',
    appId: '1:268965482512:android:f21132df9a3b46f5d9fa95',
    messagingSenderId: '268965482512',
    projectId: 'gestion-inventario-zaitec',
    storageBucket: 'gestion-inventario-zaitec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5K8zOcuL_V9UQEZQuk1AW8A9oiAD9hc',
    appId: '1:268965482512:ios:17f113e5f6384aa3d9fa95',
    messagingSenderId: '268965482512',
    projectId: 'gestion-inventario-zaitec',
    storageBucket: 'gestion-inventario-zaitec.firebasestorage.app',
    iosBundleId: 'com.example.gestionInventarioZaitec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5K8zOcuL_V9UQEZQuk1AW8A9oiAD9hc',
    appId: '1:268965482512:ios:17f113e5f6384aa3d9fa95',
    messagingSenderId: '268965482512',
    projectId: 'gestion-inventario-zaitec',
    storageBucket: 'gestion-inventario-zaitec.firebasestorage.app',
    iosBundleId: 'com.example.gestionInventarioZaitec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGHQy6POAHursOLXU45hi2buYcWh_pSHg',
    appId: '1:268965482512:web:5e665db24ca880d9d9fa95',
    messagingSenderId: '268965482512',
    projectId: 'gestion-inventario-zaitec',
    authDomain: 'gestion-inventario-zaitec.firebaseapp.com',
    storageBucket: 'gestion-inventario-zaitec.firebasestorage.app',
    measurementId: 'G-KR3V6PKK6W',
  );
}
